services:
  qemu-setup:
    image: multiarch/qemu-user-static
    container_name: qemu-setup
    privileged: true
    command: [ "--reset", "-p", "yes" ]
    deploy:
      replicas: ${COMPOSE_ENV_ENABLE_QEMU:-0}

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      platforms:
        - ${COMPOSE_ENV_PLATFORM}
      args:
        platform: ${COMPOSE_ENV_PLATFORM}
        user: ${COMPOSE_ENV_USER_DIR}
    volumes:
      - ../..:/workspaces:cached
      - ${USERPROFILE}/.aws:/home/${COMPOSE_ENV_USER_DIR}/.aws:ro
    command: [ "sleep", "infinity" ] # コンテナを起動したままにする
    depends_on:
      - qemu-setup

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: ${COMPOSE_ENV_ENABLE_LOCALSTACK:-0}

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    deploy:
      replicas: ${COMPOSE_ENV_ENABLE_POSTGRES:-0}

volumes:
  postgres-data:
