services:
  qemu-setup:
    image: multiarch/qemu-user-static
    container_name: qemu-setup
    privileged: true
    command: [ "--reset", "-p", "yes" ]
    # 実行後にコンテナを自動的に削除するオプション
    restart: "no"
    deploy:
      replicas: ${COMPOSE_ENV_ENABLE_QEMU:-0}

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      platforms:
        - ${COMPOSE_ENV_PLATFORM}
      args:
        platform: ${COMPOSE_ENV_PLATFORM}
    volumes:
      - ../..:/workspaces:cached
    # コンテナを起動したままにする
    command: [ "sleep", "infinity" ]
    network_mode: service:db
    depends_on:
      - qemu-setup

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
