services:
  qemu-setup:
    image: multiarch/qemu-user-static
    container_name: qemu-setup
    privileged: true
    command: [ "--reset", "-p", "yes" ]
    restart: "no" # 実行後にコンテナを自動的に削除するオプション
    deploy:
      replicas: ${COMPOSE_ENV_ENABLE_QEMU:-0}

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      platforms:
        - ${COMPOSE_ENV_PLATFORM}
      args:
        platform: ${COMPOSE_ENV_PLATFORM}
        user: ${COMPOSE_ENV_USER_DIR}
    volumes:
      - ../..:/workspaces:cached
      - ${USERPROFILE}/.aws:/home/${COMPOSE_ENV_USER_DIR}/.aws:ro
    command: [ "sleep", "infinity" ] # コンテナを起動したままにする
    depends_on:
      - qemu-setup

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    deploy:
      replicas: ${COMPOSE_ENV_ENABLE_POSTGRES:-0}

volumes:
  postgres-data:
